# Form implementation generated from reading ui file 'main-window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 596)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 170, 200, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"background: #6b705c;\n"
"border: 2px solid #6b705c;\n"
"border-radius: 20px;\n"
"border-color: #a5a58d;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a5a58d;\n"
"    border:2px solid #6b705c\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(250, 170, 200, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"background: #6b705c;\n"
"border: 2px solid #6b705c;\n"
"border-radius: 20px;\n"
"border-color: #a5a58d;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a5a58d;\n"
"    border:2px solid #6b705c\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(470, 170, 200, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"background: #6b705c;\n"
"border: 2px solid #6b705c;\n"
"border-radius: 20px;\n"
"border-color: #a5a58d;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a5a58d;\n"
"    border:2px solid #6b705c\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(690, 170, 200, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"background: #6b705c;\n"
"border: 2px solid #6b705c;\n"
"border-radius: 20px;\n"
"border-color: #a5a58d;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a5a58d;\n"
"    border:2px solid #6b705c\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 310, 200, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"background: #6b705c;\n"
"border: 2px solid #6b705c;\n"
"border-radius: 20px;\n"
"border-color: #a5a58d;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a5a58d;\n"
"    border:2px solid #6b705c\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(250, 310, 200, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"background: #6b705c;\n"
"border: 2px solid #6b705c;\n"
"border-radius: 20px;\n"
"border-color: #a5a58d;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a5a58d;\n"
"    border:2px solid #6b705c\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(470, 310, 200, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"background: #6b705c;\n"
"border: 2px solid #6b705c;\n"
"border-radius: 20px;\n"
"border-color: #a5a58d;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a5a58d;\n"
"    border:2px solid #6b705c\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(690, 310, 200, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"background: #6b705c;\n"
"border: 2px solid #6b705c;\n"
"border-radius: 20px;\n"
"border-color: #a5a58d;\n"
"\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #a5a58d;\n"
"    border:2px solid #6b705c\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 20, 401, 51))
        font = QtGui.QFont()
        font.setPointSize(50)
        font.setItalic(False)
        self.label.setFont(font)
        self.label.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label.setLineWidth(4)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 80, 191, 16))
        self.label_2.setStyleSheet("color: gray;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(730, 10, 231, 41))
        self.label_3.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(730, 40, 171, 20))
        self.label_4.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 918, 24))
        self.menubar.setObjectName("menubar")
        self.menuHome = QtWidgets.QMenu(self.menubar)
        self.menuHome.setObjectName("menuHome")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHome.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Register"))
        self.pushButton_3.setText(_translate("MainWindow", "Users"))
        self.pushButton_4.setText(_translate("MainWindow", "Vendors"))
        self.pushButton_5.setText(_translate("MainWindow", "Promotions"))
        self.pushButton_6.setText(_translate("MainWindow", "Inventory"))
        self.pushButton_7.setText(_translate("MainWindow", "Pricebook"))
        self.pushButton_8.setText(_translate("MainWindow", "Settings"))
        self.pushButton_9.setText(_translate("MainWindow", "Help"))
        self.label.setText(_translate("MainWindow", "Daina Market"))
        self.label_2.setText(_translate("MainWindow", "123 Main St, Boston, MA 02136"))
        self.label_3.setText(_translate("MainWindow", "Welcome: Admin "))
        self.label_4.setText(_translate("MainWindow", "Last Login : Jan 21, 2022"))
        self.menuHome.setTitle(_translate("MainWindow", "Home"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
